/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AppInfoAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppInfoAttributes{}

// AppInfoAttributes struct for AppInfoAttributes
type AppInfoAttributes struct {
	AppStoreState *AppStoreVersionState `json:"appStoreState,omitempty"`
	State *string `json:"state,omitempty"`
}

// NewAppInfoAttributes instantiates a new AppInfoAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppInfoAttributes() *AppInfoAttributes {
	this := AppInfoAttributes{}
	return &this
}

// NewAppInfoAttributesWithDefaults instantiates a new AppInfoAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppInfoAttributesWithDefaults() *AppInfoAttributes {
	this := AppInfoAttributes{}
	return &this
}

// GetAppStoreState returns the AppStoreState field value if set, zero value otherwise.
func (o *AppInfoAttributes) GetAppStoreState() AppStoreVersionState {
	if o == nil || IsNil(o.AppStoreState) {
		var ret AppStoreVersionState
		return ret
	}
	return *o.AppStoreState
}

// GetAppStoreStateOk returns a tuple with the AppStoreState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppInfoAttributes) GetAppStoreStateOk() (*AppStoreVersionState, bool) {
	if o == nil || IsNil(o.AppStoreState) {
		return nil, false
	}
	return o.AppStoreState, true
}

// HasAppStoreState returns a boolean if a field has been set.
func (o *AppInfoAttributes) HasAppStoreState() bool {
	if o != nil && !IsNil(o.AppStoreState) {
		return true
	}

	return false
}

// SetAppStoreState gets a reference to the given AppStoreVersionState and assigns it to the AppStoreState field.
func (o *AppInfoAttributes) SetAppStoreState(v AppStoreVersionState) {
	o.AppStoreState = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *AppInfoAttributes) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppInfoAttributes) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *AppInfoAttributes) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *AppInfoAttributes) SetState(v string) {
	o.State = &v
}

func (o AppInfoAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppInfoAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AppStoreState) {
		toSerialize["appStoreState"] = o.AppStoreState
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	return toSerialize, nil
}

type NullableAppInfoAttributes struct {
	value *AppInfoAttributes
	isSet bool
}

func (v NullableAppInfoAttributes) Get() *AppInfoAttributes {
	return v.value
}

func (v *NullableAppInfoAttributes) Set(val *AppInfoAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableAppInfoAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableAppInfoAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppInfoAttributes(val *AppInfoAttributes) *NullableAppInfoAttributes {
	return &NullableAppInfoAttributes{value: val, isSet: true}
}

func (v NullableAppInfoAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppInfoAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


