/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CertificateUpdateRequestData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CertificateUpdateRequestData{}

// CertificateUpdateRequestData struct for CertificateUpdateRequestData
type CertificateUpdateRequestData struct {
	Type string `json:"type"`
	Id string `json:"id"`
	Attributes *CertificateUpdateRequestDataAttributes `json:"attributes,omitempty"`
}

type _CertificateUpdateRequestData CertificateUpdateRequestData

// NewCertificateUpdateRequestData instantiates a new CertificateUpdateRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCertificateUpdateRequestData(type_ string, id string) *CertificateUpdateRequestData {
	this := CertificateUpdateRequestData{}
	this.Type = type_
	this.Id = id
	return &this
}

// NewCertificateUpdateRequestDataWithDefaults instantiates a new CertificateUpdateRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCertificateUpdateRequestDataWithDefaults() *CertificateUpdateRequestData {
	this := CertificateUpdateRequestData{}
	return &this
}

// GetType returns the Type field value
func (o *CertificateUpdateRequestData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CertificateUpdateRequestData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CertificateUpdateRequestData) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *CertificateUpdateRequestData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CertificateUpdateRequestData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CertificateUpdateRequestData) SetId(v string) {
	o.Id = v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *CertificateUpdateRequestData) GetAttributes() CertificateUpdateRequestDataAttributes {
	if o == nil || IsNil(o.Attributes) {
		var ret CertificateUpdateRequestDataAttributes
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateUpdateRequestData) GetAttributesOk() (*CertificateUpdateRequestDataAttributes, bool) {
	if o == nil || IsNil(o.Attributes) {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *CertificateUpdateRequestData) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given CertificateUpdateRequestDataAttributes and assigns it to the Attributes field.
func (o *CertificateUpdateRequestData) SetAttributes(v CertificateUpdateRequestDataAttributes) {
	o.Attributes = &v
}

func (o CertificateUpdateRequestData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CertificateUpdateRequestData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	return toSerialize, nil
}

func (o *CertificateUpdateRequestData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCertificateUpdateRequestData := _CertificateUpdateRequestData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varCertificateUpdateRequestData)

	if err != nil {
		return err
	}

	*o = CertificateUpdateRequestData(varCertificateUpdateRequestData)

	return err
}

type NullableCertificateUpdateRequestData struct {
	value *CertificateUpdateRequestData
	isSet bool
}

func (v NullableCertificateUpdateRequestData) Get() *CertificateUpdateRequestData {
	return v.value
}

func (v *NullableCertificateUpdateRequestData) Set(val *CertificateUpdateRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificateUpdateRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificateUpdateRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificateUpdateRequestData(val *CertificateUpdateRequestData) *NullableCertificateUpdateRequestData {
	return &NullableCertificateUpdateRequestData{value: val, isSet: true}
}

func (v NullableCertificateUpdateRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificateUpdateRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


