/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProfileCreateRequestDataRelationshipsCertificatesDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProfileCreateRequestDataRelationshipsCertificatesDataInner{}

// ProfileCreateRequestDataRelationshipsCertificatesDataInner struct for ProfileCreateRequestDataRelationshipsCertificatesDataInner
type ProfileCreateRequestDataRelationshipsCertificatesDataInner struct {
	Type string `json:"type"`
	Id string `json:"id"`
}

type _ProfileCreateRequestDataRelationshipsCertificatesDataInner ProfileCreateRequestDataRelationshipsCertificatesDataInner

// NewProfileCreateRequestDataRelationshipsCertificatesDataInner instantiates a new ProfileCreateRequestDataRelationshipsCertificatesDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProfileCreateRequestDataRelationshipsCertificatesDataInner(type_ string, id string) *ProfileCreateRequestDataRelationshipsCertificatesDataInner {
	this := ProfileCreateRequestDataRelationshipsCertificatesDataInner{}
	this.Type = type_
	this.Id = id
	return &this
}

// NewProfileCreateRequestDataRelationshipsCertificatesDataInnerWithDefaults instantiates a new ProfileCreateRequestDataRelationshipsCertificatesDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProfileCreateRequestDataRelationshipsCertificatesDataInnerWithDefaults() *ProfileCreateRequestDataRelationshipsCertificatesDataInner {
	this := ProfileCreateRequestDataRelationshipsCertificatesDataInner{}
	return &this
}

// GetType returns the Type field value
func (o *ProfileCreateRequestDataRelationshipsCertificatesDataInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ProfileCreateRequestDataRelationshipsCertificatesDataInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ProfileCreateRequestDataRelationshipsCertificatesDataInner) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *ProfileCreateRequestDataRelationshipsCertificatesDataInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ProfileCreateRequestDataRelationshipsCertificatesDataInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ProfileCreateRequestDataRelationshipsCertificatesDataInner) SetId(v string) {
	o.Id = v
}

func (o ProfileCreateRequestDataRelationshipsCertificatesDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProfileCreateRequestDataRelationshipsCertificatesDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *ProfileCreateRequestDataRelationshipsCertificatesDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProfileCreateRequestDataRelationshipsCertificatesDataInner := _ProfileCreateRequestDataRelationshipsCertificatesDataInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varProfileCreateRequestDataRelationshipsCertificatesDataInner)

	if err != nil {
		return err
	}

	*o = ProfileCreateRequestDataRelationshipsCertificatesDataInner(varProfileCreateRequestDataRelationshipsCertificatesDataInner)

	return err
}

type NullableProfileCreateRequestDataRelationshipsCertificatesDataInner struct {
	value *ProfileCreateRequestDataRelationshipsCertificatesDataInner
	isSet bool
}

func (v NullableProfileCreateRequestDataRelationshipsCertificatesDataInner) Get() *ProfileCreateRequestDataRelationshipsCertificatesDataInner {
	return v.value
}

func (v *NullableProfileCreateRequestDataRelationshipsCertificatesDataInner) Set(val *ProfileCreateRequestDataRelationshipsCertificatesDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableProfileCreateRequestDataRelationshipsCertificatesDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableProfileCreateRequestDataRelationshipsCertificatesDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProfileCreateRequestDataRelationshipsCertificatesDataInner(val *ProfileCreateRequestDataRelationshipsCertificatesDataInner) *NullableProfileCreateRequestDataRelationshipsCertificatesDataInner {
	return &NullableProfileCreateRequestDataRelationshipsCertificatesDataInner{value: val, isSet: true}
}

func (v NullableProfileCreateRequestDataRelationshipsCertificatesDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProfileCreateRequestDataRelationshipsCertificatesDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


