/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CertificateUpdateRequestDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CertificateUpdateRequestDataAttributes{}

// CertificateUpdateRequestDataAttributes struct for CertificateUpdateRequestDataAttributes
type CertificateUpdateRequestDataAttributes struct {
	Activated *bool `json:"activated,omitempty"`
}

// NewCertificateUpdateRequestDataAttributes instantiates a new CertificateUpdateRequestDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCertificateUpdateRequestDataAttributes() *CertificateUpdateRequestDataAttributes {
	this := CertificateUpdateRequestDataAttributes{}
	return &this
}

// NewCertificateUpdateRequestDataAttributesWithDefaults instantiates a new CertificateUpdateRequestDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCertificateUpdateRequestDataAttributesWithDefaults() *CertificateUpdateRequestDataAttributes {
	this := CertificateUpdateRequestDataAttributes{}
	return &this
}

// GetActivated returns the Activated field value if set, zero value otherwise.
func (o *CertificateUpdateRequestDataAttributes) GetActivated() bool {
	if o == nil || IsNil(o.Activated) {
		var ret bool
		return ret
	}
	return *o.Activated
}

// GetActivatedOk returns a tuple with the Activated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateUpdateRequestDataAttributes) GetActivatedOk() (*bool, bool) {
	if o == nil || IsNil(o.Activated) {
		return nil, false
	}
	return o.Activated, true
}

// HasActivated returns a boolean if a field has been set.
func (o *CertificateUpdateRequestDataAttributes) HasActivated() bool {
	if o != nil && !IsNil(o.Activated) {
		return true
	}

	return false
}

// SetActivated gets a reference to the given bool and assigns it to the Activated field.
func (o *CertificateUpdateRequestDataAttributes) SetActivated(v bool) {
	o.Activated = &v
}

func (o CertificateUpdateRequestDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CertificateUpdateRequestDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Activated) {
		toSerialize["activated"] = o.Activated
	}
	return toSerialize, nil
}

type NullableCertificateUpdateRequestDataAttributes struct {
	value *CertificateUpdateRequestDataAttributes
	isSet bool
}

func (v NullableCertificateUpdateRequestDataAttributes) Get() *CertificateUpdateRequestDataAttributes {
	return v.value
}

func (v *NullableCertificateUpdateRequestDataAttributes) Set(val *CertificateUpdateRequestDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificateUpdateRequestDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificateUpdateRequestDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificateUpdateRequestDataAttributes(val *CertificateUpdateRequestDataAttributes) *NullableCertificateUpdateRequestDataAttributes {
	return &NullableCertificateUpdateRequestDataAttributes{value: val, isSet: true}
}

func (v NullableCertificateUpdateRequestDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificateUpdateRequestDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


