/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BundleIdResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BundleIdResponse{}

// BundleIdResponse struct for BundleIdResponse
type BundleIdResponse struct {
	Data BundleId `json:"data"`
	Included []BundleIdResponseIncludedInner `json:"included,omitempty"`
}

type _BundleIdResponse BundleIdResponse

// NewBundleIdResponse instantiates a new BundleIdResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBundleIdResponse(data BundleId) *BundleIdResponse {
	this := BundleIdResponse{}
	this.Data = data
	return &this
}

// NewBundleIdResponseWithDefaults instantiates a new BundleIdResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBundleIdResponseWithDefaults() *BundleIdResponse {
	this := BundleIdResponse{}
	return &this
}

// GetData returns the Data field value
func (o *BundleIdResponse) GetData() BundleId {
	if o == nil {
		var ret BundleId
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *BundleIdResponse) GetDataOk() (*BundleId, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *BundleIdResponse) SetData(v BundleId) {
	o.Data = v
}

// GetIncluded returns the Included field value if set, zero value otherwise.
func (o *BundleIdResponse) GetIncluded() []BundleIdResponseIncludedInner {
	if o == nil || IsNil(o.Included) {
		var ret []BundleIdResponseIncludedInner
		return ret
	}
	return o.Included
}

// GetIncludedOk returns a tuple with the Included field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BundleIdResponse) GetIncludedOk() ([]BundleIdResponseIncludedInner, bool) {
	if o == nil || IsNil(o.Included) {
		return nil, false
	}
	return o.Included, true
}

// HasIncluded returns a boolean if a field has been set.
func (o *BundleIdResponse) HasIncluded() bool {
	if o != nil && !IsNil(o.Included) {
		return true
	}

	return false
}

// SetIncluded gets a reference to the given []BundleIdResponseIncludedInner and assigns it to the Included field.
func (o *BundleIdResponse) SetIncluded(v []BundleIdResponseIncludedInner) {
	o.Included = v
}

func (o BundleIdResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BundleIdResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Included) {
		toSerialize["included"] = o.Included
	}
	return toSerialize, nil
}

func (o *BundleIdResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBundleIdResponse := _BundleIdResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varBundleIdResponse)

	if err != nil {
		return err
	}

	*o = BundleIdResponse(varBundleIdResponse)

	return err
}

type NullableBundleIdResponse struct {
	value *BundleIdResponse
	isSet bool
}

func (v NullableBundleIdResponse) Get() *BundleIdResponse {
	return v.value
}

func (v *NullableBundleIdResponse) Set(val *BundleIdResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBundleIdResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBundleIdResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBundleIdResponse(val *BundleIdResponse) *NullableBundleIdResponse {
	return &NullableBundleIdResponse{value: val, isSet: true}
}

func (v NullableBundleIdResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBundleIdResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


