/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CertificateUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CertificateUpdateRequest{}

// CertificateUpdateRequest struct for CertificateUpdateRequest
type CertificateUpdateRequest struct {
	Data CertificateUpdateRequestData `json:"data"`
}

type _CertificateUpdateRequest CertificateUpdateRequest

// NewCertificateUpdateRequest instantiates a new CertificateUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCertificateUpdateRequest(data CertificateUpdateRequestData) *CertificateUpdateRequest {
	this := CertificateUpdateRequest{}
	this.Data = data
	return &this
}

// NewCertificateUpdateRequestWithDefaults instantiates a new CertificateUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCertificateUpdateRequestWithDefaults() *CertificateUpdateRequest {
	this := CertificateUpdateRequest{}
	return &this
}

// GetData returns the Data field value
func (o *CertificateUpdateRequest) GetData() CertificateUpdateRequestData {
	if o == nil {
		var ret CertificateUpdateRequestData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CertificateUpdateRequest) GetDataOk() (*CertificateUpdateRequestData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CertificateUpdateRequest) SetData(v CertificateUpdateRequestData) {
	o.Data = v
}

func (o CertificateUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CertificateUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CertificateUpdateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCertificateUpdateRequest := _CertificateUpdateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varCertificateUpdateRequest)

	if err != nil {
		return err
	}

	*o = CertificateUpdateRequest(varCertificateUpdateRequest)

	return err
}

type NullableCertificateUpdateRequest struct {
	value *CertificateUpdateRequest
	isSet bool
}

func (v NullableCertificateUpdateRequest) Get() *CertificateUpdateRequest {
	return v.value
}

func (v *NullableCertificateUpdateRequest) Set(val *CertificateUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificateUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificateUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificateUpdateRequest(val *CertificateUpdateRequest) *NullableCertificateUpdateRequest {
	return &NullableCertificateUpdateRequest{value: val, isSet: true}
}

func (v NullableCertificateUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificateUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


