/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BundleIdRelationshipsAppData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BundleIdRelationshipsAppData{}

// BundleIdRelationshipsAppData struct for BundleIdRelationshipsAppData
type BundleIdRelationshipsAppData struct {
	Type string `json:"type"`
	Id string `json:"id"`
}

type _BundleIdRelationshipsAppData BundleIdRelationshipsAppData

// NewBundleIdRelationshipsAppData instantiates a new BundleIdRelationshipsAppData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBundleIdRelationshipsAppData(type_ string, id string) *BundleIdRelationshipsAppData {
	this := BundleIdRelationshipsAppData{}
	this.Type = type_
	this.Id = id
	return &this
}

// NewBundleIdRelationshipsAppDataWithDefaults instantiates a new BundleIdRelationshipsAppData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBundleIdRelationshipsAppDataWithDefaults() *BundleIdRelationshipsAppData {
	this := BundleIdRelationshipsAppData{}
	return &this
}

// GetType returns the Type field value
func (o *BundleIdRelationshipsAppData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *BundleIdRelationshipsAppData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *BundleIdRelationshipsAppData) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *BundleIdRelationshipsAppData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BundleIdRelationshipsAppData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BundleIdRelationshipsAppData) SetId(v string) {
	o.Id = v
}

func (o BundleIdRelationshipsAppData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BundleIdRelationshipsAppData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *BundleIdRelationshipsAppData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBundleIdRelationshipsAppData := _BundleIdRelationshipsAppData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varBundleIdRelationshipsAppData)

	if err != nil {
		return err
	}

	*o = BundleIdRelationshipsAppData(varBundleIdRelationshipsAppData)

	return err
}

type NullableBundleIdRelationshipsAppData struct {
	value *BundleIdRelationshipsAppData
	isSet bool
}

func (v NullableBundleIdRelationshipsAppData) Get() *BundleIdRelationshipsAppData {
	return v.value
}

func (v *NullableBundleIdRelationshipsAppData) Set(val *BundleIdRelationshipsAppData) {
	v.value = val
	v.isSet = true
}

func (v NullableBundleIdRelationshipsAppData) IsSet() bool {
	return v.isSet
}

func (v *NullableBundleIdRelationshipsAppData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBundleIdRelationshipsAppData(val *BundleIdRelationshipsAppData) *NullableBundleIdRelationshipsAppData {
	return &NullableBundleIdRelationshipsAppData{value: val, isSet: true}
}

func (v NullableBundleIdRelationshipsAppData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBundleIdRelationshipsAppData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


