/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProfileCreateRequestDataRelationshipsDevicesDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProfileCreateRequestDataRelationshipsDevicesDataInner{}

// ProfileCreateRequestDataRelationshipsDevicesDataInner struct for ProfileCreateRequestDataRelationshipsDevicesDataInner
type ProfileCreateRequestDataRelationshipsDevicesDataInner struct {
	Type string `json:"type"`
	Id string `json:"id"`
}

type _ProfileCreateRequestDataRelationshipsDevicesDataInner ProfileCreateRequestDataRelationshipsDevicesDataInner

// NewProfileCreateRequestDataRelationshipsDevicesDataInner instantiates a new ProfileCreateRequestDataRelationshipsDevicesDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProfileCreateRequestDataRelationshipsDevicesDataInner(type_ string, id string) *ProfileCreateRequestDataRelationshipsDevicesDataInner {
	this := ProfileCreateRequestDataRelationshipsDevicesDataInner{}
	this.Type = type_
	this.Id = id
	return &this
}

// NewProfileCreateRequestDataRelationshipsDevicesDataInnerWithDefaults instantiates a new ProfileCreateRequestDataRelationshipsDevicesDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProfileCreateRequestDataRelationshipsDevicesDataInnerWithDefaults() *ProfileCreateRequestDataRelationshipsDevicesDataInner {
	this := ProfileCreateRequestDataRelationshipsDevicesDataInner{}
	return &this
}

// GetType returns the Type field value
func (o *ProfileCreateRequestDataRelationshipsDevicesDataInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ProfileCreateRequestDataRelationshipsDevicesDataInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ProfileCreateRequestDataRelationshipsDevicesDataInner) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *ProfileCreateRequestDataRelationshipsDevicesDataInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ProfileCreateRequestDataRelationshipsDevicesDataInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ProfileCreateRequestDataRelationshipsDevicesDataInner) SetId(v string) {
	o.Id = v
}

func (o ProfileCreateRequestDataRelationshipsDevicesDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProfileCreateRequestDataRelationshipsDevicesDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *ProfileCreateRequestDataRelationshipsDevicesDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProfileCreateRequestDataRelationshipsDevicesDataInner := _ProfileCreateRequestDataRelationshipsDevicesDataInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varProfileCreateRequestDataRelationshipsDevicesDataInner)

	if err != nil {
		return err
	}

	*o = ProfileCreateRequestDataRelationshipsDevicesDataInner(varProfileCreateRequestDataRelationshipsDevicesDataInner)

	return err
}

type NullableProfileCreateRequestDataRelationshipsDevicesDataInner struct {
	value *ProfileCreateRequestDataRelationshipsDevicesDataInner
	isSet bool
}

func (v NullableProfileCreateRequestDataRelationshipsDevicesDataInner) Get() *ProfileCreateRequestDataRelationshipsDevicesDataInner {
	return v.value
}

func (v *NullableProfileCreateRequestDataRelationshipsDevicesDataInner) Set(val *ProfileCreateRequestDataRelationshipsDevicesDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableProfileCreateRequestDataRelationshipsDevicesDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableProfileCreateRequestDataRelationshipsDevicesDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProfileCreateRequestDataRelationshipsDevicesDataInner(val *ProfileCreateRequestDataRelationshipsDevicesDataInner) *NullableProfileCreateRequestDataRelationshipsDevicesDataInner {
	return &NullableProfileCreateRequestDataRelationshipsDevicesDataInner{value: val, isSet: true}
}

func (v NullableProfileCreateRequestDataRelationshipsDevicesDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProfileCreateRequestDataRelationshipsDevicesDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


