/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CertificatesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CertificatesResponse{}

// CertificatesResponse struct for CertificatesResponse
type CertificatesResponse struct {
	Data []Certificate `json:"data"`
}

type _CertificatesResponse CertificatesResponse

// NewCertificatesResponse instantiates a new CertificatesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCertificatesResponse(data []Certificate) *CertificatesResponse {
	this := CertificatesResponse{}
	this.Data = data
	return &this
}

// NewCertificatesResponseWithDefaults instantiates a new CertificatesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCertificatesResponseWithDefaults() *CertificatesResponse {
	this := CertificatesResponse{}
	return &this
}

// GetData returns the Data field value
func (o *CertificatesResponse) GetData() []Certificate {
	if o == nil {
		var ret []Certificate
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CertificatesResponse) GetDataOk() ([]Certificate, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *CertificatesResponse) SetData(v []Certificate) {
	o.Data = v
}

func (o CertificatesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CertificatesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CertificatesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCertificatesResponse := _CertificatesResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varCertificatesResponse)

	if err != nil {
		return err
	}

	*o = CertificatesResponse(varCertificatesResponse)

	return err
}

type NullableCertificatesResponse struct {
	value *CertificatesResponse
	isSet bool
}

func (v NullableCertificatesResponse) Get() *CertificatesResponse {
	return v.value
}

func (v *NullableCertificatesResponse) Set(val *CertificatesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificatesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificatesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificatesResponse(val *CertificatesResponse) *NullableCertificatesResponse {
	return &NullableCertificatesResponse{value: val, isSet: true}
}

func (v NullableCertificatesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificatesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


